### ISSUE TITLE
Ability to generate past world border

### ISSUE THREAD

**Issue by mxs42** [Trivernis/spigot-chunkmaster#14]
I want to generate world past existing world border but because of [this](https://github.com/Trivernis/spigot-chunkmaster/blob/master/src/main/kotlin/net/trivernis/chunkmaster/lib/generation/GenerationTaskPaper.kt#L39) plugin stops generation since `borderReached` checks world border.
I think plugin shouldn't check world border if you specify amount of chunks manually.

**Comment by Trivernis** [comment]
The plugin checks if the vanilla world border is reached which is very unlikely to happen with the default radius. If you decreased the world border by command and want to generate past it, I wonder what the use of that would be since it is not possible to wander around behind the world border (for very long).

**Comment by mxs42** [comment]
I want to generate on a live server. I mean, currently I have 40K world border and I want to expand it, that's why I need to generate past existing world border so players still can not go outside until I fully generate extended radius.

**Comment by mxs42** [comment]
It's not a big deal, I can fork it and tune myself, just thought it can be useful because I was confused when it stopped at 40% when I specified radius manually.

**Comment by Trivernis** [comment]
Oh, okay. Maybe I could add a config option for that in a future release.

**Comment by mxs42** [comment]
Made some changes in https://github.com/mxs42/spigot-chunkmaster
Maybe it could be useful for somebody
