### ISSUE TITLE
Is there a chunks/sec limiter?

### ISSUE THREAD

**Issue by BijuuKrunos** [Trivernis/spigot-chunkmaster#25]
Heyho realy nice plugin love it.
But I want to setup that Chunkmaster is allowed to generade more than 20 Chunks/sec.
I configured my config that he should do huge more than that. but it seems to be captched by 20.

My config.
`generation:
  period: 1
  chunks-per-step: 10
  chunk-skips-per-step: 200
  mspt-pause-threshold: 1000
  pause-on-join: true
  max-pending-chunks: 100
  max-loaded-chunks: 100
  ignore-worldborder: false`

Is this a Bug?

**Comment by Trivernis** [comment]
No, this is probably not a bug but your server is probably just unable to generate more than 20 chunks per second. The generation process is very heavy on the cpu so that probably limits it.

**Comment by BijuuKrunos** [comment]
Dont think so. my server is on 40% not more. he can easy more. there have to be a cap

**Comment by Trivernis** [comment]
Are you using spigot or paper?

**Comment by BijuuKrunos** [comment]
paper of course :*

**Comment by Trivernis** [comment]
Hmm that should at least speed up the saving of chunks. 
I think the 1.15 version of paper doesn't support multithreaded chunk generation (yet) so that might be one reason why it doesn't use the whole processing power.
As for the plugin it doesn't have a hard coded limit so 20 chunks/sec might be the maximum speed.
