### ISSUE TITLE
ChunkMaster hasn't loaded all the chunks in my world

### ISSUE THREAD

**Issue by Southpaw1496** [Trivernis/spigot-chunkmaster#26]
I'm getting an issue where if I run `chunkmaster generate world` which I believe is supposed to generate all chunks up to the world boarder it hasn't. Below is a screenshot of Dynmap for you to observe.
![Screenshot 2020-02-27 at 4 15 18 pm](https://user-images.githubusercontent.com/44805409/75462956-f8033d00-597c-11ea-8ea4-1bb31491a610.png)
As you can see it neatly stops before it is finished, leaving a sort of corner out of the generation process. I know it's not dynmap because you can see the little bits that players have generated. I've repeatedly run the generate command but it just runs for a few minutes at 1000CPS and then stops. I've re-rendered Dynmap but nothing has happened. 
I'm using Beta 0.14 and the latest version of paper which at the time of writing is Build #121

**Comment by Trivernis** [comment]
Is the red border also the vanilla world border? If it is then the generation stops because the plugin has reached the world border. You can turn off that behavior in the config file.

**Comment by Southpaw1496** [comment]
The red boarder is the vanilla boarder.

**Comment by Trivernis** [comment]
Okay, since the plugin generates in a spiral it reaches the border in the lower right and stops generating. You can either turn that off as I mentioned before or use the not yet released [1.15 version](https://46-208644898-gh.circle-artifacts.com/0/build/chunkmaster-0.15-beta.jar) which allows you to set a different center for the generation.

**Comment by Southpaw1496** [comment]
So if I turn it off it’ll just keep going to infinity, will it?

**Comment by Trivernis** [comment]
Yeah, you should set a limit if you turn it off.

**Comment by Southpaw1496** [comment]
So if I set I set my World Boarder to 8000 blocks and I set this to 8000 will it generate to the worldboarder?
Also, why does the plugin generate in a spiral if the world boarder is a square?

**Comment by Trivernis** [comment]
If the world border is 8000 blocks in radius you can create a generation task for that with `chm generate world 8000 blockradius`.
The plugin generates in a spiral because the most common use case is that you don't generate the whole world at once. Since it can take a while you don't want to have a slice of chunks at the very top of a square generated but the chunks around the spawn which you will visit more likely.

**Comment by Southpaw1496** [comment]
Perhaps you should add square generation as a config in the future, but thanks for the help!
