### ISSUE TITLE
How to increase the generation speed

### ISSUE THREAD

**Issue by Poatita** [Trivernis/spigot-chunkmaster#42]
Hello, I am having a problem with the world generation. No matter what you touch of the settings it does not affect the generation of chunks. Currently I have an i9 and 7gb of ram and it generates 25 chunks per second at most.

P.S: you should create a discord to solve minor doubts like this n.n

**Comment by naughtius-maximus-8492** [comment]
Same thing here. Running a Ryzen 5 3600 and by default, it generates at around 9 ch/s. The only setting which increases the generation speed is period where decreasing from 2 to 1 means my generation speed goes to a solid 20.0 ch/s. However tweaking chunk-skips-per-step, mspt-pause-threshold, max-pending-chunks and max-loaded-chunks makes _no_ difference whatsoever.

Using Paper to do this as well so it should benefit from Async chunks as well.

**Comment by Trivernis** [comment]
> P.S: you should create a discord to solve minor doubts like this n.n

I feel like that might be even more work than I have now for answering requests


What tps is the server reporting? If the value is still at 20 you should increase the value for chunks-per-step even further. 
Also make sure to set the value for max loaded chunks at 10*chunks-per-step to make sure that the plugin doesn't unload chunks every other run.

You should also analyse how much cpu the minecraft main thread uses since most of the chunk generation work still is single threaded.
The hard drive speed also limits the generation speed because it slows down the saving of chunks.
