### ISSUE TITLE
[BUG] Chunkmaster doesn't accept world name with spaces

### ISSUE THREAD

**Issue by haliknihudas666** [Trivernis/spigot-chunkmaster#96]
**Describe the bug**
Chunkmaster on the console doesn't accept any spaces even tho i put this 3 ` ' " before and after the command

**Expected behavior**
Chunkmaster is expected to accept world name with spaces

**Screenshots**
![image](https://user-images.githubusercontent.com/6942408/89898786-e2748d80-dc13-11ea-96cd-4f9025ef26b0.png)

**Server (please complete the following information):**
 - OS: Windows and Linux
 - Specs: Intel Xeon E5-2673 v4 64 Cores | 256GB
 - Java Version: 8 and JDK Version 14
 - Minecraft Server Version: PaperMC 1.16.1 #131
 - Plugin Version: 1.3.2

**Comment by Nieblue** [comment]
I am having the same issue with this plugin.  My server name is Nies Chaos, and when I am trying to pre-generate the end it throws an error because it can not find Chaos_the_end.  That would be because the folder is named Nies Chaos_the_end.  I am using the plugin better ends and they recommended your plugin as the go-to for pregenration, but I can not get it to work please help.
